blank_issues_enabled: false
contact_links:
  - name: ğŸ“± Calculadora de Notas Comunidad
    url: https://github.com/Nachovn114/Calcular_Notas_App/discussions
    about: Por favor haz preguntas generales y discute ideas aquÃ­.
  - name: ğŸ“ DocumentaciÃ³n
    url: https://github.com/Nachovn114/Calcular_Notas_App/wiki
    about: AsegÃºrate de revisar nuestra documentaciÃ³n primero. 